apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: defectdojo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/iamfet/sec-gitops-online-boutique
    targetRevision: main
    path: defectdojo-app
  destination:
    server: https://kubernetes.default.svc
    namespace: defectdojo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true