name: Destroy Infrastructure

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
    inputs:
      confirm_destroy:
        description: 'Type "destroy" to confirm infrastructure destruction'
        required: true

env:
  TF_VERSION: "1.12.0"
  TF_IN_AUTOMATION: true
  TF_LOG: INFO
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm_destroy == 'destroy'
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ACTIONS_AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: GitHubActions
          
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Create Terraform plugin cache directory
        run: |
          mkdir -p ~/.terraform.d/plugin-cache
          echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

      - name: Cache Terraform
        uses: actions/cache@v4.2.3
        with:
          path: ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Terraform Init
        run: |
          # Initialize with remote backend
          terraform init
      
      - name: Terraform Destroy
        run: |
          terraform destroy \
            -var="user_for_admin_role=${{ secrets.ADMIN_USER_ARN }}" \
            -var="user_for_dev_role=${{ secrets.DEV_USER_ARN }}" \
            -auto-approve
            
      - name: Clean up backend
        run: |
          echo "WARNING: Backend cleanup should be done manually after confirming all infrastructure is destroyed"
          echo "To destroy backend: cd backend && terraform init && terraform destroy"
        continue-on-error: true